#pragma once

#define LASER_TEST

#define LASER_PIN 8
#define WATER_LEVEL_PINS {0, 1, 2}
#define WATER_LEVEL_PINS_COUNT 3
#define WATER_LEVEL_ENABLE_PIN  3


#define WATER_EMPTY_VALUE 1

#define TRANSMITTER_DELAY 200