#pragma once

#define LASER_INPUT_PIN 2
#define BUZZER_PIN 0
#define INDICATOR_PINS {1, 3, 4, 5}
#define INDICATOR_PINS_COUNT 4
#define MOTOR_STOP_PIN 6

#define WATER_EMPTY_VALUE 2
#define MAX_WATER_LEVEL 3
#define RECEIVE_TIME_GAP 2000
// #define RECEIVE_TIME_GAP 5000
#define LASER_PULSE_DURATION 100
#define LASER_MIN_PULSE_DURATION 50


#define NO_RECEIVE_ERROR_TIME 70000
// #define NO_RECEIVE_ERROR_TIME 10000

#define TANK_FULL_ALARM_TIME 15000


